#!/bin/sh

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
case "$1" in
  start)
	msg_starting gopherd
	daemon /usr/sbin/gopherd -d
	touch /var/lock/subsys/gopherd
	;;
  stop)
	msg_stopping gopherd
	killproc gopherd
	rm -f /var/lock/subsys/gopherd
	;;
  status)
	status gopherd
	;;
  restart|reload)
	$0 stop
	$0 start
	;;
  *)
	msg_usage "$0 {start|stop|status|restart|reload}"
	exit 1
esac
